substitutions:
  _IMAGE_TAG: "1"


steps:

# Build the CI container image from the first build stage
- id: build-ollama-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ollama:${_IMAGE_TAG}', '.']

# Push the container image to Container Registry
- id: push-ollama-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ollama:${_IMAGE_TAG}']

# Deploy Ollama image to Cloud Run
- id: deploy-ollama-image-as-service
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'devassist'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ollama:${_IMAGE_TAG}'
  - '--region'
  - 'europe-west1'
  - '--concurrency=4'
  - '--set-env-vars'
  - 'OLLAMA_NUM_PARALLEL=4'
  - '--cpu=4'
  - '--gpu=1'
  - '--gpu-type=nvidia-l4'
  - '--no-gpu-zonal-redundancy'
  - '--max-instances=1'
  - '--memory=16Gi'
  - '--service-account=runtime@$PROJECT_ID.iam.gserviceaccount.com'
  - '--no-allow-unauthenticated'
  - '--no-cpu-throttling'
  - '--timeout=600'


images:
- 'gcr.io/$PROJECT_ID/ollama:${_IMAGE_TAG}'


options:
  logging: CLOUD_LOGGING_ONLY
